name: Feature Request
description: Use this template for submitting feature requests for the PSCloudPC module
title: "🚀 [Feature Request]: "
labels: [feature]
assignees:
  - 

body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to suggest a new feature. Please provide the following details:
  - type: input
    id: contact
    attributes:
      label: Contact Details
      description: How can we get in touch with you if we need more info?
      placeholder: ex. email@example.com
    validations:
      required: true
  - type: input
    id: feature
    attributes:
      label: Feature
      description: Is your feature request related to a problem? Please describe.
      placeholder: A clear and concise description of what the problem is.
    validations:
      required: true

  - type: textarea
    id: feature_description
    attributes:
      label: Feature Description
      description: Can you describe the feature in detail?
      placeholder: A clear and concise description of what you want to happen.
    validations:
      required: false
  - type: textarea
    id: feature_outcome
    attributes:
      label: Feature Output
      description: What is the expected output for the feature?
      placeholder: Enter your expected output here...
    validations:
      required: true
  - type: textarea
    id: feature_implementation
    attributes:
      label: Possible implementation
      description: What is the expected output for the feature?
      placeholder: Not obligatory, but suggest an idea for implementing the addition or change.
    validations:
      required: false